[routes]

; Test
POST /crypto/encryption = Controllers\CryptoController->encryption
POST /crypto/decryption = Controllers\CryptoController->decryption

; Categories
POST /categories/create = Controllers\CategoriesController->create
POST /categories/update = Controllers\CategoriesController->update
GET /categories/list = Controllers\CategoriesController->list
POST /categories/delete = Controllers\CategoriesController->delete

; Users
POST /users/create = Controllers\UsersController->register
POST /users/login = Controllers\UsersController->login
POST /users/update = Controllers\UsersController->update
POST /users/forgot-password = Controllers\UsersController->forgotPassword
GET /users/list = Controllers\UsersController->listAll
POST /users/delete = Controllers\UsersController->delete
GET /users/profile = Controllers\UsersController->profile

; Accounts
POST /accounts/create = Controllers\AccountsController->create
POST /accounts/update = Controllers\AccountsController->update
GET /accounts/list = Controllers\AccountsController->list
POST /accounts/delete = Controllers\AccountsController->delete

; Transactions
POST /transactions/create = Controllers\TransactionsController->create
POST /transactions/update = Controllers\TransactionsController->update
GET /transactions/list = Controllers\TransactionsController->list
POST /transactions/delete = Controllers\TransactionsController->delete

; Transfers
POST /transfers/create = Controllers\TransfersController->create
POST /transfers/update = Controllers\TransfersController->update
GET /transfers/list = Controllers\TransfersController->list
POST /transfers/delete = Controllers\TransfersController->delete