[routes]

; Test
POST /crypto/encryption = Controllers\CryptoController->encryption
POST /crypto/decryption = Controllers\CryptoController->decryption

; Categories
POST /categories/register = Controllers\CategoriesController->register
POST /categories/update = Controllers\CategoriesController->update
GET /categories/list = Controllers\CategoriesController->list
POST /categories/delete = Controllers\CategoriesController->delete

; Users
POST /users/register = Controllers\UsersController->register
POST /users/login = Controllers\UsersController->login
POST /users/update = Controllers\UsersController->update
POST /users/forgot-password = Controllers\UsersController->forgotPassword
GET /users/list = Controllers\UsersController->list
POST /users/delete = Controllers\UsersController->delete
GET /users/profile = Controllers\UsersController->profile

; Accounts
POST /accounts/register = Controllers\AccountsController->register
POST /accounts/update = Controllers\AccountsController->update
GET /accounts/list = Controllers\AccountsController->list
POST /accounts/delete = Controllers\AccountsController->delete

; Transactions
POST /transactions/register = Controllers\TransactionsController->register
POST /transactions/update = Controllers\TransactionsController->update
GET /transactions/list = Controllers\TransactionsController->list
POST /transactions/delete = Controllers\TransactionsController->delete

; Transfers
POST /transfers/register = Controllers\TransfersController->register
POST /transfers/update = Controllers\TransfersController->update
GET /transfers/list = Controllers\TransfersController->list
POST /transfers/delete = Controllers\TransfersController->delete

; Budgets
POST /budgets/register = Controllers\BudgetsController->register
POST /budgets/update = Controllers\BudgetsController->update
GET /budgets/list = Controllers\BudgetsController->list
GET /budgets/summary = Controllers\BudgetsController->summary
POST /budgets/delete = Controllers\BudgetsController->delete